# Generated by Django 5.0.6 on 2024-06-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
