# Generated by Django 5.0.6 on 2024-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_update', models.CharField(blank=True, max_length=200, unique=True)),
            ],
        ),
    ]
